/**
 * GhostNetwork/Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReactionType = 0 | 1 | 2 | 3 | 4 | 5;

export const ReactionType = {
    NUMBER_0: 0 as ReactionType,
    NUMBER_1: 1 as ReactionType,
    NUMBER_2: 2 as ReactionType,
    NUMBER_3: 3 as ReactionType,
    NUMBER_4: 4 as ReactionType,
    NUMBER_5: 5 as ReactionType
};

